fun main() {
/*
   ChatService.getChats(1)
   ChatService.getChats(2)
   ChatService.sendMessage(3,2,"Привет")
   Thread.sleep(1000)
   ChatService.sendMessage(4,2,"Привет1")
   Thread.sleep(1000)
   ChatService.sendMessage(1,2,"Привет1")
   Thread.sleep(1000)
   ChatService.sendMessage(1,2,"Привет2")
   Thread.sleep(1000)
   ChatService.sendMessage(99,2,"Привет3")
   Thread.sleep(1000)
   ChatService.sendMessage(2,1,"Привет4")
   Thread.sleep(1000)
   ChatService.sendMessage(1,2,"Привет5")
   Thread.sleep(1000)
   ChatService.sendMessage(1,2,"Привет6")
   Thread.sleep(1000)
   ChatService.sendMessage(4,2,"Привет1")
   Thread.sleep(1000)
   ChatService.sendMessage(3,2,"Привет")
   Thread.sleep(1000)
   ChatService.sendMessage(4,2,"Привет1")


   ChatService.persons[1]?.get(2)?.open()
   ChatService.persons[2]?.get(4)?.open()

   ChatService.getChats(1)
   ChatService.getChats(2)
   ChatService.persons[2]?.get(1)?.open()
   ChatService.persons[2]?.get(1)?.deleteMessage(4)
   ChatService.editMessage(3,"ИЗМЕНЕННЫЙ ТЕКСТ")
   ChatService.persons[2]?.get(1)?.open()
   ChatService.getChats(2)
   ChatService.deleteChat(2,4)
   ChatService.createChat(5,2)
   println("Непрочитанных чатов : ${ChatService.getUnreadChatsCount(2)}")
   ChatService.persons[2]?.get(99)?.open()
   ChatService.persons[2]?.get(99)?.deleteMessage(5)
   ChatService.persons[2]?.get(99)?.open()
*/

}